name: gem_consumer_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.1+175

environment:
  #sdk: ">=2.7.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  #provider: ^5.0.0
  provider: ^6.0.1
  graphql_flutter: ^5.0.0-nullsafety.2
  jwt_decoder: ^2.0.0
  http: ^0.13.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_svg: ^0.21.0+1
  font_awesome_flutter: ^9.0.0
  image_picker: ^0.8.3
  collection: ^1.15.0
  pinput: ^1.2.0
  flutter_facebook_auth: ^3.4.0
  sign_in_with_apple: ^3.3.0
  google_maps_flutter: ^2.0.6
  geolocator: ^7.7.0
  geocoding: ^2.0.0
  flutter_widget_from_html_core: ^0.6.1+3
  smooth_page_indicator: ^0.2.3
  location: ^4.2.0
  app_settings: ^4.1.0
  flutter_google_places: ^0.3.0
  google_places_for_flutter: ^1.0.1
  flutter_rating_bar: ^4.0.0
  timeago: ^3.1.0
  status_change: ^1.0.0
  rms_mobile_xdk_flutter: ^3.30.1
  map_pin_picker: ^0.0.1
  flutter_slidable: ^0.6.0
  geocoder: ^0.2.1
  material_floating_search_bar: ^0.3.4
  awesome_dropdown: ^0.0.1
  #firebase_messaging: ^10.0.5
  firebase_messaging: ^11.2.11
  device_info: ^2.0.2
  package_info: ^2.0.2
  firebase_core: ^1.13.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_analytics: ^8.3.0
  firebase_remote_config: ^0.10.0+4
  launch_review: ^3.0.1
  flutter_spinkit: ^5.1.0
  zendesk2: ^2.0.0+1
  cached_network_image: ^3.1.0
  file_picker: ^4.0.2
  url_launcher: ^6.0.10
  modal_bottom_sheet: ^1.0.0+1
  flutter_overlay_loader: ^0.0.2
  email_validator: ^0.1.0
  flutter_dotenv: ^5.0.2
  shimmer: ^2.0.0
  configurable_expansion_tile_null_safety: ^2.0.0
  shared_preferences: ^2.0.13
  platform: ^3.1.0
  shared_preferences_android: ^2.0.11
  flutter_app_badger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - .env.production
    - assets/i18n/
    - assets/images/onboarding/
    - assets/images/service-type/
    - assets/images/home/
    - assets/images/account-page/
    - assets/images/splash/
    - assets/images/
    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Arial Rounded MT Light
      fonts:
        - asset: assets/fonts/ArialRoundedMTLight.ttf
    - family: Arial Rounded MT Bold
      fonts:
        - asset: assets/fonts/ArialRoundedBold.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
